// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"database/sql"
)

type TblFile struct {
	ID int32
	// 文件hash
	FileSha1 string
	// 文件名
	FileName string
	// 文件大小
	FileSize sql.NullInt64
	// 文件存储位置
	FileAddr string
	// 创建日期
	CreateAt sql.NullTime
	// 更新日期
	UpdateAt sql.NullTime
	// 状态(可用/禁用/已删除等状态)
	Status int32
	// 备用字段1
	Ext1 sql.NullInt32
	// 备用字段2
	Ext2 sql.NullString
}

type TblUser struct {
	ID int32
	// 用户名
	UserName string
	// 用户encoded密码
	UserPwd string
	// 邮箱
	Email sql.NullString
	// 手机号
	Phone sql.NullString
	// 邮箱是否已验证
	EmailValidated sql.NullBool
	// 手机号是否已验证
	PhoneValidated sql.NullBool
	// 注册日期
	SignupAt sql.NullTime
	// 最后活跃时间戳
	LastActive sql.NullTime
	// 用户属性
	Profile sql.NullString
	// 账户状态(启用/禁用/锁定/标记删除等)
	Status int32
}

type TblUserFile struct {
	ID       int32
	UserName string
	// 文件hash
	FileSha1 string
	// 文件大小
	FileSize sql.NullInt64
	// 文件名
	FileName string
	// 上传时间
	UploadAt sql.NullTime
	// 最后修改时间
	LastUpdate sql.NullTime
	// 文件状态(0正常1已删除2禁用)
	Status int32
}

type TblUserToken struct {
	ID int32
	// 用户名
	UserName string
	// 用户登录token
	UserToken string
	// 过期日期
	ExpireAt sql.NullTime
}
